export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO';
export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS';
export const AGREGAR_PROYECTOS = 'AGREGAR_PROYECTOS';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const SELECCIONAR_PROYECTO = 'SELECCIONAR_PROYECTO';
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO';


export const SELECCIONAR_TAREAS = 'SELECCIONAR_TAREAS';
export const AGREGAR_TAREA = 'AGREGAR_TAREA';
